[package]
name = "avored-rust-cms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.7", features = ["multipart"] }
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tower-http = { version = "0.6.1", features = ["fs", "cors"] }
dotenvy = "0.15.7"
axum-extra = { version = "0.9.4", features = ["cookie", "cookie-signed"] }
futures = "0.3.30"
argon2 = "0.5.3"
rand = "0.8.5"
urlencoding = "2.1.3"
serde_json = "1.0.128"
surrealdb = { version = "2.0.2", features = ["kv-rocksdb", "kv-mem"] }
jsonwebtoken = "9.3.0"
chrono = { version = "0.4.38", features = [] }
email_address = "0.2.9"
rust-i18n = "3.1.2"
lettre = { version = "0.11.9", features = ["tokio1-native-tls"] }
handlebars = "6.1.0"
utoipa = "4.2.3"
juniper = "0.16.1"
juniper_axum = { version = "0.1.0", features = ["subscriptions"] }
tokio-stream = "0.1.16"
dashmap = "6.1.0"


[dev-dependencies]
mockall = "0.13.0"
tower = { version = "0.5.1", features = ["util"] }
